logging:
  level:
    ROOT: INFO
    org.springframework.cloud:
      config: DEBUG
      kubernetes: DEBUG

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  cloud:
    kubernetes:
      enabled: true

eureka:
  client:
    enabled: false
