spring:
  datasource:
    url: jdbc:sqlserver://mssql:1433;databaseName=Audit
    username: sa
    password: Admin123admin
    
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG   
