spring:
  datasource:
    url: jdbc:sqlserver://mssql:1433;databaseName=Audit
    username: sa
    password: AscendDB1!
    
logging:
  level:
    ROOT: DEBUG
    org.springframework.cloud:
      config: DEBUG
      kubernetes: DEBUG
