spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=Audit
    username: sa
    password: Admin123admin
    
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG    
